### PR TITLE
add evolution items and HQ pictures

### PR DESCRIPTION
**Pull request by Jcolomar**

### CODE REVIEW

**Comment by pogarek** [comment]
does it work ? I thought these items (files) must be called with numbers.

**Comment by Jcolomar** [comment]
I didnt check how is called. But pictures of new items is needed also

**Comment by pogarek** [comment]
ok, I'll try to test it later. I'm heavily busy till thursday

**Comment by pogarek** [comment]
@Jcolomar I'm sorry, but items needs to be renamed. For example: http://127.0.0.1:8000/image/items/1102.png that is the link to Kings Rocks on my webui... Can you rename it and try the PR again ?... No offense, Mate..

**Pull request closed without merging**
