### PR TITLE
Log patch

### PR DESCRIPTION
**Pull request by AshtonAU**

### CODE REVIEW

**Comment by mmixx** [comment]
Your commits were from July 27? Have you updated your fork on the latest commits?

**Comment by oralunal** [comment]
Has conflicts, please resolve it.

**Comment by Jcolomar** [comment]
Can someone close this? '28 Sep 2016'

**Comment by goedzo** [comment]
close please

**Comment by nbq** [comment]
As per @goedzo I am closing this PR

**Pull request closed without merging**
