### PR TITLE
update trainer location through websocket

### PR DESCRIPTION
**Pull request by rawgni**
only the first position needs to be read from web/location-USERNAME.json file

the rest are updated through websocket.

should work with current master

PokemonGoF/PokemonGo-Bot#5084

### CODE REVIEW

**Comment by oralunal** [comment]
There is known issue [https://github.com/PokemonGoF/PokemonGo-Bot/issues/5035](url)

I'm using polylinewalker and trainer location is not changing in web ui :(

**Comment by oralunal** [comment]
It's now fixed in dev issue, waiting dev to master merge.

**Comment by oralunal** [comment]
Reverted it.. There was problems
1. User path isn't drawing default.
2. User pan isn't working.
3. Lot's of error message about JSON's.

Can you make an update with the latest Master.

**Comment by rawgni** [comment]
@oralunal hm.. my bad. i guess we will leave it as is since we are moving toward mtqq soon.

**Pull request merged**
