### PR TITLE
Dynamic ip address for the socket.io connection

### PR DESCRIPTION
**Pull request by chr0nu5**

### CODE REVIEW

**Comment by mmixx** [comment]
You need to pair this IP from the config.json you're using unless someone can set a dynamic IP on the config settings...

```
    "websocket": {
        "start_embedded_server": true,
        "server_url": "127.0.0.1:4000"
    }
```

**Comment by chr0nu5** [comment]
We could use `0.0.0.0` to make it dynamic too. Is this a good approach? Will make a PR

**Comment by mmixx** [comment]
Yep... just tested it on my copy and it works... just need to change the default `server_url` on the `config.json.example` from `127.0.0.1` to `0.0.0.0`...

**Comment by chr0nu5** [comment]
Hi @mmixx, i do not know if you are a mantainer on the main repo, but [here](https://github.com/PokemonGoF/PokemonGo-Bot/pull/5545) is the PR.

**Comment by mmixx** [comment]
I'm not. but it will be reviewed in a couple of hours... :)

**Comment by rawgni** [comment]
@chr0nu5 isn't it better if it is configured through the userdata.json file ?

For example, I have the bot running on a different machine, I would like pogo web to run on localhost. Thus, the socket should connect to the IP of that machine and not to localhost.

**Comment by chr0nu5** [comment]
Hi @rawgni, you are very correct. I made an update on the PR to use the userdata.js

**Comment by rawgni** [comment]
@chr0nu5 might want to use a list, ie. for people with multiple bot. Each bot will probably be running on separate socket port.

**Comment by chr0nu5** [comment]
Hmm, this is a great idea, but i think that it would make some great changes on the file. Should i make another PR or update this one? This is what i think the userdata.js file should look like:

```
 var userInfo = {
  users: [{
    username: "username",
    socketAddress: "0.0.0.0:4000"
  }],
  userZoom: false,
  userPath: true,
  zoom: 16,
  userFollow: true,
  gMapsAPIKey: "YOUR_API_KEY_HERE"
 };
```

Is that ok? 🤔

**Comment by rawgni** [comment]
yeah. it does seems that a lot have to change in the main code :(

hm.. maybe should ask @solderzzc and @oralunal for their thoughts.

**Comment by mmixx** [comment]
If ever, I'll start on changing the codes to accommodate the changes on `userdata.js`...

**Comment by chr0nu5** [comment]
I`ll make it on my fork and, if it becomes stable, i will make another PR. For now, the current PR is good or will not be merged?

**Comment by mmixx** [comment]
I'm done modifying my copy to comply with the `userdata.js` sample you provided... It now connects to multiple users on different ports set...

```
 var userInfo = {
    users: [{
        username: "xxx@gmail.com",
        socketAddress: "0.0.0.0:4000"
    },{
        username: "ptc_account",
        socketAddress: "0.0.0.0:5000"
    }],
    userZoom: true,
    userPath: true,
    zoom: 16,
    userFollow: true,
    gMapsAPIKey: "Google_MAP_key"
 }; 
```

EDIT: And also, when clicking **FIND** button... It will follow the specific bot that you want...

EDIT: Or if you click any button on the bot's menu, it will automatically put the bot you pick on center...

**Comment by solderzzc** [comment]
👍

**Pull request merged**
