### PR TITLE
display pokemon level info

### LINKED ISSUE #32: Show Level of Pokemons
Would it be possible to also show the level of the pokemon?

Makes it easier to decide wich one to power-up.

### PR DESCRIPTION
**Pull request by rawgni**
closes #32

### CODE REVIEW

**Comment by oralunal** [comment]
Is bot giving level data? Let me take a look.

Edit: I can't see level element of pokemons. Is it in the dev branch?

**Comment by rawgni** [comment]
yes dev branch

**Comment by oralunal** [comment]
@rawgni okay, thank you for this PR. I'm waiting merge to master.

**Comment by oralunal** [comment]
Your branch has conflicts.

**Comment by oralunal** [comment]
Why did you delete the userdata.js.example... Your work is working fine. There is something wrong at bot side.

**Pull request merged**
