### PR TITLE
Fixes #84

### LINKED ISSUE #84: Unexpected token '>' line 292 main.js
When trying to browse the web interface, I get this error:
http://0.0.0.0:8000/js/main.js @292: SytaxError: Unexpected Token '>'

### PR DESCRIPTION
**Pull request by Smarticles101**

### CODE REVIEW

**Review by mmixx — APPROVED** [review]
Thanks for the fix...

**Comment by Smarticles101** [comment]
I just wanted to say thanks for allowing me to do this pull request @mmixx. It really started me off with open source and I have come a long way since a year ago when this happened. 😀

**Comment by nbq** [comment]
@Smarticles101 We can always use some contributors still to the project. Feel free to join our discord and message Holoshed

**Comment by Smarticles101** [comment]
@nbq I'd be up to that. What's the link to the discord?

**Pull request merged**
